version: "3.1"

services:
  weworks_postgres:
    container_name: weworks_postgres
    image: postgres:latest
    restart: always
    volumes:
      - pgdata_live:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: weworks
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: weworks

  weworks:
    container_name: weworks
    image: weworks/weworks:latest
    ports:
      - 1000:3000
      - 1001:5003
# If running via Docker on a hypervisor, enable DNS.
#    dns:
#      - 1.1.1.1
#      - 8.8.8.8
    restart: always
    depends_on:
      - weworks_postgres
    environment:
      DB_USERNAME: "weworks"
      DB_PASSWORD: "12345"
      DB_HOST: "weworks_postgres"
      SECRET: 'weworks4life'

volumes:
 pgdata_live:
